(setq c-recognize-knr-p nil)
(custom-set-variables
 '(recent-files-menu-path (quote ("file")))
 '(ultex-use-bib-cite t)
 '(font-lock-auto-fontify t)
 '(Info-additional-search-directory-list (quote ("/usr/share/info/xemacs" "/usr/share/info")))
 '(template-alt-comment-syntax-alist (quote ((t "/** " " */"))))
 '(locale-package nil)
 '(speedbar-show-unknown-files t)
 '(modeline-click-swaps-buffers nil)
 '(package-get-dir "~/elisp_download")
 '(ecb-methods-general-face (quote ecb-methods-general-face))
 '(gutter-buffers-tab-visible-p nil)
 '(ps-paper-type (quote a4))
 '(pgg-package t)
 '(ultex-use-auctex t)
 '(paren-mode (quote blink-paren) nil (paren))
 '(progress-feedback-style (quote small))
 '(speedbar-fetch-etags-arguments (quote ("--members" "-I" "-o" "-")) t)
 '(w3-do-scripting t)
 '(ecb-new-ecb-frame t)
 '(egg-its-package nil)
 '(display-warning-minimum-level (quote error))
 '(LaTeX-left-comment-regexp "%")
 '(smtpmail-smtp-server "t2.technion.ac.il")
 '(highlight-completion-mode t nil (highlight-completion))
 '(skk-package nil)
 '(vm-primary-inbox "~/mail/INBOX.local")
 '(display-time-24hr-format t)
 '(buffers-tab-sort-function nil)
 '(font-lock-mode-enable-list (quote (c++-mode dired-mode dired-mode c-mode)))
 '(ultex-use-imenu t)
 '(mouse-avoidance-mode (quote exile) nil (avoid))
 '(pc-select-selection-keys-only t)
 '(ultex-match-parens t)
 '(buffers-menu-submenus-for-groups-p nil)
 '(auto-save-directory "~/.xemacs/.autosave")
 '(save-place t)
 '(recent-files-actions-on-top nil)
 '(ispell-extra-args (quote ("-W" "3")))
 '(speedbar-use-tool-tips-flag t)
 '(speedbar-update-speed 1 t)
 '(column-number-mode t)
 '(lazy-shot-mode t nil (lazy-shot))
 '(track-eol t)
 '(recent-files-dont-include nil)
 '(ultex-match-brackets t)
 '(fast-lock-mode t nil (fast-lock))
 '(recent-files-permanent-submenu t)
 '(jde-jdk-registry (quote (("1.4.1_02" . "/usr/java/j2sdk1.4.1_02/"))))
 '(save-options-file "~/.xemacs/options" t)
 '(recent-files-save-file "~/.xemacs/.recent-files_list.el")
 '(gnuserv-program (concat exec-directory "/gnuserv"))
 '(recent-files-commands-submenu t)
 '(ruby-modes-package t)
 '(progress-feedback-use-echo-area t)
 '(psgml-dtds-package t)
 '(speedbar-use-images t)
 '(ultex-init-file "~/.xemacs/.ultex")
 '(desktop-enable t nil (desktop))
 '(lookup-package nil)
 '(c-auto-newline t t)
 '(minibuffer-smart-completion-tracking-behavior t)
 '(ediff-use-toolbar-p t)
 '(latin-unity-package nil)
 '(Manual-switches nil)
 '(session-mode-enable-list nil)
 '(fortran-modes-package t)
 '(dired-gnutar-program "tar")
 '(display-time-echo-area t)
 '(auto-insert-directory "~/.xemacs/auto-insert-templates/" t)
 '(display-time-ignore-read-mail nil)
 '(mule-base-package nil)
 '(jka-compr-temp-name-template "/tmp/.michael/jka-com")
 '(tags-build-completion-table t)
 '(save-place-file "~/.xemacs/.emacs_places")
 '(auto-insert-query (quote other))
 '(visible-bell t)
 '(dired-show-ls-switches t)
 '(pui-package-install-dest-dir nil)
 '(max-specpdl-size 6000)
 '(dired-find-subdir t)
 '(savehist-length 10000)
 '(ultex-use-font-latex t)
 '(ecrypto-package t)
 '(ultex-use-color t)
 '(pending-delete-mode t nil (pending-del))
 '(leim-package nil)
 '(tmpl-template-dir-list (quote ("//usr/share/xemacs/xemacs-packages/etc/hm--html-menus/" "~/.xemacs/templates/")))
 '(buffers-menu-sort-function (quote sort-buffers-menu-by-mode-then-alphabetically))
 '(toolbar-visible-p nil)
 '(debug-on-error nil)
 '(dired-ls-F-marks-symlinks t)
 '(toolbar-mail-reader (quote vm))
 '(dired-listing-switches "-alhGg")
 '(url-proxy-services nil)
 '(c-report-syntactic-errors t)
 '(default-gutter-position (quote top))
 '(dired-directory t t)
 '(package-get-require-signed-base-updates nil)
 '(diary-file "~/.xemacs/.diary")
 '(line-number-mode t)
 '(buffers-tab-grouping-regexp nil)
 '(tags-auto-read-changed-tag-files t)
 '(speedbar-use-imenu-flag t)
 '(buffers-tab-filter-functions nil)
 '(mule-ucs-package nil)
 '(edict-package nil)
 '(bookmark-use-annotations t)
 '(buffers-menu-grouping-function nil)
 '(kill-whole-line t)
 '(display-time-day-and-date t)
 '(stack-trace-on-error nil)
 '(user-full-name "Michael Pavlovsky " t)
 '(recent-files-add-menu-before nil)
 '(savehist-file "~/.xemacs/.emacs-history")
 '(dired-backup-if-overwrite t)
 '(frame-background-mode nil)
 '(session-save-file "~/.xemacs/.session")
 '(Info-inhibit-toolbar nil)
 '(pc-select-meta-moves-sexps t)
 '(bookmark-default-file "~/.xemacs/.emacs.bmk" t)
 '(mouse-yank-at-point t)
 '(save-completions-file-name "~/.xemacs/.completions")
 '(hs-special-modes-alist (quote ((c-mode "{" "}") (c++-mode "{" "}") (c++-mode "^.*/**" "^.**/"))) t)
 '(hide-ifdef-initially t)
 '(buffers-tab-face (quote buffers-tab))
 '(message-directory "~/mail/")
 '(ispell-look-command "looksave-options-file")
 '(dired-local-variables-file "~/.xemacs/.dired")
 '(frame-title-format (quote ("%S: " (buffer-file-name "%f" (dired-directory dired-directory "%b")) " %l:%c")) t)
 '(speedbar-fetch-etags-command "/usr/bin/etags" t)
 '(template-default-directories (quote ("~/.xemacs/templates/")))
 '(complex-buffers-menu-p nil)
 '(gnus-select-method (quote (nntp "news.teranews.com")))
 '(perl-modes-package t)
 '(LaTeX-item-indent 0)
 '(user-mail-address "spavlov@techst02.technion.ac.il")
 '(list-directory-verbose-switches "")
 '(query-user-mail-address nil)
 '(shell-completion-fignore (quote ("~" "#")))
 '(highlight-completion-list-external (quote (t t t t t t t t t t)))
 '(w3-do-incremental-display t)
 '(docbookide-package t)
 '(template-derivation-alist (quote (((t "" t)) ((t nil null) nil nil t 1) (("TEMPLATE" "" t)) (("TEMPLATE" "" ".cpp" ".c{pp,xx}") "" "" ".cpp"))))
 '(font-lock-mode t nil (font-lock))
 '(smtpmail-default-smtp-server "t2.technion.ac.il")
 '(pc-selection-mode t)
 '(recent-files-include-save-now t))
(custom-set-faces
 '(default ((t (:size "12pt" :family "Courier New"))))
 '(pointer ((t (:background "red"))) t)
 '(custom-set-face ((((class color)) (:foreground "blue"))))
 '(info-node ((t (:foreground "blueviolet" :bold t :underline nil))))
 '(widget-field-face ((((class grayscale color) (background light)) (:underline t))))
 '(dired-face-permissions ((((type x pm mswindows) (class color)) (:foreground "darkblue"))))
 '(dired-face-flagged ((((type x pm mswindows) (class color) (background light)) (:size "10" :strikethru t))))
 '(man-italic ((t (:family "" :bold t :italic t))))
 '(modeline-buffer-id ((t (:foreground "blue4" :background "wheat2" :size "" :family "" :dim nil :bold nil :italic nil :underline nil :strikethru nil :inverse-video nil))))
 '(modeline-mousable ((t (:foreground "firebrick" :bold t :background "wheat2"))))
 '(gui-element ((t (:background "wheat2" :size "14"))) t)
 '(widget ((t (:size "14"))) t)
 '(hyper-apropos-hyperlink ((((class color) (background light)) (:foreground "cornflowerblue"))))
 '(toolbar ((t (:background "wheat2"))) t)
 '(vm-monochrome-image ((t (:foreground "black"))) t)
 '(man-heading ((t (:foreground "blue" :bold t))))
 '(font-lock-warning-face ((((class color) (background light)) (:foreground "Red"))))
 '(man-xref ((t (:bold t :underline t))))
 '(bold ((t (:foreground "black" :size "10pt" :bold t))))
 '(diary-face ((t (:foreground "IndianRed"))))
 '(modeline ((t (:background "wheat2"))))
 '(dired-face-boring ((((type x pm mswindows) (class color grayscale) (background light)) (:foreground "gray40"))))
 '(buffers-tab ((t (:foreground "black" :background "wheat2"))) t))
(put 'narrow-to-region 'disabled nil)
(put 'LaTeX-hide-environment 'disabled nil)
(put 'overwrite-mode 'disabled nil)
